name: "Upload release artifact for Linux"
on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        quic:
          - quic
          - noquic
        doc:
          - TRUE
          - FALSE
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install doxygen
      - name: Build
        run: |
          rm -rf build.paho
          mkdir build.paho
          cd build.paho
          echo "pwd $PWD"
          WithQuic=FALSE
          if [[ ${{ matrix.quic }} == "quic" ]];
          then
          WithQuic=TRUE
          fi
          cmake -DPAHO_BUILD_STATIC=FALSE -DPAHO_BUILD_SHARED=TRUE -DCMAKE_BUILD_TYPE=Debug -DPAHO_WITH_SSL=TRUE -DOPENSSL_ROOT_DIR= -DPAHO_BUILD_DOCUMENTATION=FALSE -DPAHO_BUILD_SAMPLES=TRUE -DPAHO_HIGH_PERFORMANCE=TRUE -DPAHO_BUILD_DOCUMENTATION="${{ matrix.doc }}" -DPAHO_WITH_MSQUIC="${WithQuic} " ..
          cmake --build .
      - name: package
        run: |
          cd build.paho
          cpack --verbose         
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: packages
          path: /home/runner/work/paho.mqtt.c/paho.mqtt.c/build.paho/Eclipse-Paho-MQTT-C-*.tar.gz

  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs:
      - build
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: packages
          path: packages
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: Eclipse-Paho-MQTT-C ${{ github.ref_name }} Released
          body: Eclipse-Paho-MQTT-C ${{ github.ref_name }} Released
          files: packages/*
          draft: false
          prerelease: false
